import { ModuleInfo } from './types';

export const MODULES_DATA: ModuleInfo[] = [
  {
    id: 'stm32h7',
    name: 'STM32H7 Microcontroller Core',
    acronym: 'STM32H743XI',
    description: 'High-performance ARM Cortex-M7 running at 480 MHz. Outfitted with double-precision FPU, hardware image DSP accelerators, direct graphic memory Chrom-ART engine, and dense local RAM blocks.',
    role: 'Central AI Engine & Processing Hub. Responsible for raw camera sensor bus control, running on-chip tinyML models (such as MobileNet v2 or YOLO-Nano), managing display refresh frames, computing distance vectors, and coordinating wireless packet uploads.',
    protocol: 'Internal Bus / AXI Crossbar Controller',
    pins: [
      'PC8..12 (SDIO_D0..D4)',
      'PD3, PG9 (SDIO_CMD/CLK)',
      'PE4..6, PI4..7 (DCMI_D0..D7)',
      'PA4, PH5 (DCMI_HSYNC/VSYNC)',
      'PK0..7, PJ0..15 (LTDC RGB888)',
      'PB8, PB9 (I2C1_SCL/SDA)',
      'PA0 (EXTI0_TRIG_INPUT)',
      'PA1 (TIM1_CH2_ECHO_INPUT)'
    ],
    specs: {
      'Clock speed': '480 MHz Frequency',
      'Processor Core': 'ARM Cortex-M7 (32-Bit)',
      'Flash Memory': '2 Megabytes (Dual Bank)',
      'Local RAM': '1.4 Megabytes Total SRAM',
      'Edge Compiler': 'STM32Cube.AI Engine',
      'Graphics': 'Chrom-ART DMA2D Accelerator'
    },
    voltage: '3.3V IO / 1.2V Core Logic',
    speed: '1027 DMIPS / 2.02 CoreMark/MHz',
    status: 'idle',
    color: '#06b6d4'
  },
  {
    id: 'ov5640',
    name: 'OV5640 Camera Module',
    acronym: 'OV5640-CAM',
    description: 'High-performance 5 Megapixel CMOS color image sensor featuring on-board automatic focus mechanics, raw pixel processors, and custom image compression encoders (JPEG/YUV/RGB).',
    role: 'Visual Capture Front-End. Directs high-framerate raw pixel matrices over a 10-line parallel bus to the microcontroller’s Digital Camera Interface (DCMI) block.',
    protocol: 'DCMI Parallel Bus + I2C (SCCB Control Block)',
    pins: [
      'DCMI_D0 .. DCMI_D7 (Data Bus)',
      'DCMI_HSYNC, DCMI_VSYNC (Sync)',
      'DCMI_PIXCLK (Pixel Clock Line)',
      'SCCB_SDA, SCCB_SCL (I2C Controls)',
      'CAM_PWDN, CAM_RESET (Control GPIOs)'
    ],
    specs: {
      'Sensor Grid': '2592 x 1944 Active Pixels (5.0 MP)',
      'Optical Format': '1/4-inch Focal Sensor',
      'Framerate Capacity': '30 fps @ 1080p Full-HD / 60 fps @ 720p',
      'Focus Handler': 'On-board Digital VCM Driver',
      'Pixel Pitch': '1.4 µm x 1.4 µm OmniBSI-2 Tech',
      'Output Modes': 'RAW RGB, YUV422, Compressed JPEG'
    },
    voltage: '2.8V Analog / 1.8V Digital Core / 3.3V IO',
    speed: '24.00 MHz Native Clock Speed',
    status: 'idle',
    color: '#ec4899'
  },
  {
    id: 'lcd',
    name: 'RGB TFT Display Panel',
    acronym: 'TFT-LCD-WVGA',
    description: 'Vibrant 4.3" high-resolution Liquid Crystal display running clean parallel red-green-blue signal lines. Driven directly by the microcontroller Chrom-ART memory-to-memory block.',
    role: 'Telemetry & Viewfinder HUD Output. Visualizes real-time camera imagery alongside bounding boxes generated by the edge object-detection algorithm, active confidence metrics, and diagnostics.',
    protocol: '24-bit Parallel RGB (LTDC controller interface)',
    pins: [
      'LTDC_R0 .. LTDC_R7 (Red Data Bus)',
      'LTDC_G0 .. LTDC_G7 (Green Data Bus)',
      'LTDC_B0 .. LTDC_B7 (Blue Data Bus)',
      'LTDC_CLK, LTDC_DE (Timing & Enable)',
      'LTDC_HSYNC, LTDC_VSYNC (Sync Pins)',
      'LCD_BL_PWM (Backlight Intensity GPIO)'
    ],
    specs: {
      'Panel Width/Height': '800 x 480 Active WVGA Matrix',
      'Color Gamut': '16.7 Million Colors (24-bit RGB)',
      'Screen Backlit': 'Dynamic 12-LED Constant Current PWM',
      'Refresh Speed': '60 Hz Progressive Scan',
      'TFT Driver Model': 'OTA7001 / ILI9806 High-Speed Controller',
      'Display Plane': 'IPS Wide-View Angle Panel'
    },
    voltage: '3.3V Chip Power / 5.0V LED Backlight Line',
    speed: '30.00 MHz LTDC Bus Clock',
    status: 'idle',
    color: '#eab308'
  },
  {
    id: 'ultrasonic',
    name: 'Ultrasonic Distance Sensor',
    acronym: 'SRF-SONIC',
    description: 'Precision dual-transducer spatial radar array that generates 40 kHz high-frequency sonic bursts and captures timed reflections with nanosecond stopwatch precision.',
    role: 'Proximity detection and Spatial Depth Trigger. Scans the forward sight cone for physical obstacles. Feeds microsecond signal feedback to STM32H7 input capture timers to compute target distance.',
    protocol: 'GPIO Trigger Pulse + High-Resolution Timer Echo Capture',
    pins: [
      'TRIG_LINE (PA0 EXTI Out Trigger)',
      'ECHO_LINE (PA1 TIM1 Input Channel 2)',
      'GND (Common Ground Shield)',
      'VCC (Direct VBUS 5V Power Transducer)'
    ],
    specs: {
      'Sound Transduction': '40 kHz Concentric Transmissions',
      'Ranging Span': '2 cm to 450 cm (Non-Contact)',
      'Accuracy Deviation': 'Within 3.0 mm Vector Deviation',
      'Sensing Aperture': '15° Measurement Dispersion Cone',
      'Trigger Burst Pulse': '10 Microsecond High GPIO Pulse',
      'Echo Signal Format': 'Microsec High pulse matching sound run time'
    },
    voltage: '5.0V Power / 3.3V Level-Shifted IO Translators',
    speed: '343 meters/second Wave Rate (20ms refresh)',
    status: 'idle',
    color: '#a855f7'
  },
  {
    id: 'wifi',
    name: 'WiFi Communication Module',
    acronym: 'ESP-SDIO-NET',
    description: 'Low-latency WiFi & Bluetooth system-on-chip equipped with an integrated power amplifier, low-noise amplifiers, security decryptors, and an on-board gold microstrip trace antenna.',
    role: 'High-speed Telemetry Gateway. Channels compressed image bytes, IoT analytics, and bounding box arrays off-site via a 4-bit multiplexed SDIO parallel bus.',
    protocol: 'SDIO v2.0 (Dual-edge 4-bit High-speed Interface)',
    pins: [
      'SDIO_CLK (PC12 Clock Routing)',
      'SDIO_CMD (PD2 Command/Response Frame)',
      'SDIO_D0 .. SDIO_D3 (4-bit Parallel Bus IO)',
      'NET_EN (Power/Shutoff Control EXTI)',
      'NET_INT (H7 Interruption Handshake)'
    ],
    specs: {
      'Wireless Protocols': '802.11 b/g/n Wifi Standard (2.4 GHz)',
      'Max Signal Output': '20.5 dBm Peak Transmission Level',
      'Security Suite': 'WPA3 Enterprise Access / Native TLS 1.3 Client',
      'Bandwidth Standard': 'SDIO clocking up to 50 MHz Peak',
      'Power Savings': 'Deep Sleep Core State < 15 µA Draw',
      'RF Interface': 'On-board Impedance-Matched PCB Loop'
    },
    voltage: '3.3V Dedicated LDO Regulator Line',
    speed: '50.00 Mbps SDIO Frame Transmissions',
    status: 'idle',
    color: '#10b981'
  },
  {
    id: 'cloud',
    name: 'Edge AI Enterprise Cloud',
    acronym: 'API-CLOUD-DB',
    description: 'High-availability server stack hosting real-time IoT gateways, time-series data storage caches, deep analytical models, and firmware image distribution nodes.',
    role: 'Unified Telemetry Storage & Deep AI Training Server. Aggregates live object detection registers, logs ambient ranges, visualizes trends, and handles OTA (Over-The-Air) binary updates.',
    protocol: 'HTTPS / JSON Core API + Secure MQTT Publish/Subscribe',
    pins: [
      'Wireless Radio Link',
      'Virtual REST Handshake Port',
      'Secure WebSocket Tunneling Engine'
    ],
    specs: {
      'Server Protocols': 'Secure MQTT Client Websockets / REST Webhooks',
      'NoSQL Database': 'Real-Time Firestore & Time-Series Ledger',
      'Cloud Core Compute': 'Dynamic Edge Inference Clustering',
      'SSL Validation': 'SHA-256 Root Digital Security Signature',
      'Firmware Bank': 'Binary Archive for OTA flash upgrades',
      'Access Controls': 'OAuth Token Validation Headers'
    },
    voltage: 'Cloud System Grid Power',
    speed: '1.20 Gbps Wireless Ingress Bandwidth',
    status: 'idle',
    color: '#f97316'
  }
];
